# -*- coding: utf-8 -*-
"""Learning_Python_Week_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7Z_UXlWjJwZG2Datp7TNoKNrXdOHzN_
"""

a = 2
b = 2

a == b

a = 'value'
b = 'value'

a == b

a = 2
b = 4

a != b

a = 2
b = 2

a != b

a = 4
b = 2

a > b

a = 4
b = 5

a > b

a = 4
b = 6

a < b

a = 8
b = 6

a < b

a = 5
b = 2

a >= b

a = 5
b = 5
v
a >= b

a = 5
b = 10

a >= b

a = 5
b = 8

a <= b

a = 8
b = 8

a <= b

a = 10
b = 8

a <= b

a = 20

if (a > 16) :
	print("You can pass")

print("move on")

a = 20

if (a < 20) :
	print("You can pass")
elif (a == 20) :
  print("You're too old for this machine")

print("move on")

a = 56

if (a < 20) :
	print("You can pass")
elif (a == 20) :
  print("You're too old for this machine")
else :
  print("You can't be here. Move on!")

print("move on")

# Mulai

# input umur
umur = int(input("Berapa umur kamu = "))

if (umur >= 17) : # Jika umur lebih sama dengan 17

  print("Boleh membuat SIM") # Boleh membuat SIM

else : # Jika umur tidak lebih sama dengan 17

  print("Belum boleh membuat SIM") # Tidak boleh membuat SIM

# Selesai

# Mulai

print("===== Sistem Input Nilai =====")
print("")

# Input Nilai

nilai = int(input("Berapa nilai kamu = ")) # input Nilai
grade = str # Variable grade

if (nilai >= 90) : # Jika nilai lebih sama dengan 90
  grade = "A" # Grade A
elif (nilai >= 80) : # Jika nilai lebih sama dengan 80
  grade = "B+" # Grade B+
elif (nilai >= 70) : # Jika nilai lebih sama dengan 70
  grade = "B" # Grade B
elif (nilai >= 60) : # Jika nilai lebih sama dengan 60
  grade = "C+" # Grade C+
elif (nilai >= 50) : # Jika nilai lebih sama dengan 50
  grade = "C" # Grade C
elif (nilai >= 40) : # Jika nilai lebih sama dengan 40
  grade = "D" # Grade D
else : # Jika nilai kurang dari 40
  grade = "E" # Grade E

print("")
print("Grade kamu adalah = {}".format(grade)) # Print Grade

# Selesai

# Mulai

print("===== Sistem Input Nilai =====")
print("")

# Input Nilai

nilai = float(input("Berapa nilai kamu = ")) # input Nilai
grade = str # Variable grade

if (nilai >= 80) : # Jika nilai lebih sama dengan 80
  grade = "A" # Grade A
elif (nilai >= 77.5) : # Jika nilai lebih sama dengan 77.5
  grade = "A-" # Grade A-
elif (nilai >= 75) : # Jika nilai lebih sama dengan 75
  grade = "A/B" # Grade A/B
elif (nilai >= 72.5) : # Jika nilai lebih sama dengan 72.5
  grade = "B+" # Grade B+
elif (nilai >= 70) : # Jika nilai lebih sama dengan 70
  grade = "B" # Grade B
elif (nilai >= 67.5) : # Jika nilai lebih sama dengan 67.5
  grade = "B-" # Grade B-
elif (nilai >= 65) : # Jika nilai lebih sama dengan dari 65
  grade = "B/C" # Grade B/C
elif (nilai >= 62.5) : # Jika nilai lebih sama dengan dari 62.5
  grade = "C+" # Grade C+
elif (nilai >= 60) : # Jika nilai lebih sama dengan dari 60
  grade = "C" # Grade C
elif (nilai >= 55) : # Jika nilai lebih sama dengan dari 55
  grade = "C-" # Grade C-
elif (nilai >= 50) : # Jika nilai lebih sama dengan dari 50
  grade = "C/D" # Grade C/D
elif (nilai >= 45) : # Jika nilai lebih sama dengan dari 45
  grade = "D+" # Grade D+
elif (nilai >= 40) : # Jika nilai lebih sama dengan dari 40
  grade = "D" # Grade D
else : # Jika nilai kurang dari 40
  grade = "E" # Grade E

print("")
print("Grade kamu adalah = {}".format(grade)) # Print Grade

# Selesai