# -*- coding: utf-8 -*-
"""Learning-Python-Week-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgXw1MvPJS1vWHAxEnP2Nsa8b1Za3q7M
"""

#Print String Text

print('Hello Python!')

import sys
print(sys.version)

# put your comment here

print('the green text is your comment')

# print string as error message

print('Hello, Python!')

print('My biodata :')
print('')
print('Name   : Farrel Apriandry')
print('Number : 2430506056')
print('Addres : Magelang, Central Java, Indonesia')
print('Height : 169cm')
print('Weight : 73kg')

print('\033[1mUNIVERSITAS TIDAR\033[0m')
print('Universitas Tidar merupakan Perguruan Tinggi Pemerintah atau Perguruan Tinggi Negeri yang telah ditetapkan berdasarkan Peraturan Presiden Republik Indonesia Nomor 23 Tahun 2014 pada tanggal 1 April 2014.')
print('')
print('\033[1mPROGRAM PENDIDIKAN TEKNOLOGI INFORMASI\033[0m')
print('Program Pendidikan Teknologi Informasi adalah sebuah Program studi yang tersedia di Untidar dibawah naungan Fakultas Teknik')