# -*- coding: utf-8 -*-
"""Learning-Python-Week06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUlVbkMYvznjFmHaIWt-NeZZ2QuQfHR_
"""

range(3)

age = [17,19,21]
N = len(age)

for i in range(N):
    print(age[i])

for i in range(0, 5):
    print(i)

list = [1,2,3,4,5]
for number in list:
    print(number)

number = ['-1', '0', '1', '2']

for i in range(0, 3):
    print("Before number ", i, 'is',  number[i])
    squares[i] = 'weight'
    print("After number ", i, 'is',  number[i])

color = ['red', 'yellow', 'green', 'blue']

for i, color in enumerate(color):
    i = i + 1
    print(i, color)

age = [17, 21, 23, 25]

i = 0
number = 0

while(number != age[2]):
    number = age[i]
    i = i + 1
    print(number)

print("It took ", i ,"repetitions to get out of loop.")

for i in range(1, 3):
    for j in range(1, 3):
        print(f"i = {i}, j = {j}")

ln = int(input("Jumlah baris: "))
spc = ln - 1

for i in range(ln):
  print(" " * spc + "* " * (i + 1))
  spc -= 1

x = int(input("Jumlah baris: "))

def pascal(a, b) :
  if b in (0, a) :
    return 1
  return pascal(a - 1, b - 1) + pascal(a - 1, b)

for row in range(x) :
  print(" " * (x - row - 1), end="")
  for b in range(row + 1) :
    print(pascal(row, b), end=" ")
  print()

def pascal(a, b) :
  if b in (0, a) :
    return 1
  return pascal(a - 1, b - 1) + pascal(a - 1, b)

def hasilBaris(x):
  jumlah = 0
  for b in range(x):
    jumlah += pascal(x - 1, b)
  return jumlah

x = int(input("Input jumlah baris: "))
print(hasilBaris(x))